# Site wide configuration

title: Hubot Messenger adapter
locale: en_US
description: A Facebook Messenger adapter for the Hubot framework
search: false
baseurl: "" # the subpath of your site, e.g. /blog
url: https://spilio.github.io/hubot-messenger-adapter
github: https://github.com/spilio/hubot-messenger-adapter


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge


# Site owner
owner:
  name: Chris Spiliotopoulos
  email: chrysanthos.spiliotopoulos@gmail.com
  linkedin: https://www.linkedin.com/in/spilio
